# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_autoclicker(object):
    def setupUi(self, autoclicker):
        autoclicker.setObjectName("autoclicker")
        autoclicker.resize(300, 300)
        autoclicker.setMinimumSize(QtCore.QSize(300, 300))
        autoclicker.setMaximumSize(QtCore.QSize(300, 300))
        autoclicker.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        autoclicker.setAnimated(True)
        autoclicker.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=autoclicker)
        self.centralwidget.setObjectName("centralwidget")
        self.start_click_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.start_click_label.setGeometry(QtCore.QRect(20, 50, 121, 20))
        self.start_click_label.setObjectName("start_click_label")
        self.end_click_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.end_click_label.setGeometry(QtCore.QRect(20, 90, 121, 20))
        self.end_click_label.setObjectName("end_click_label")
        self.delay_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.delay_label.setGeometry(QtCore.QRect(20, 130, 121, 16))
        self.delay_label.setObjectName("delay_label")
        self.startClick_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.startClick_lineEdit.setGeometry(QtCore.QRect(150, 50, 89, 19))
        self.startClick_lineEdit.setObjectName("startClick_lineEdit")
        self.endClick_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.endClick_lineEdit.setGeometry(QtCore.QRect(150, 90, 89, 19))
        self.endClick_lineEdit.setObjectName("endClick_lineEdit")
        self.delay_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.delay_lineEdit.setGeometry(QtCore.QRect(150, 130, 89, 19))
        self.delay_lineEdit.setObjectName("delay_lineEdit")
        self.program_status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.program_status_label.setGeometry(QtCore.QRect(40, 170, 91, 16))
        self.program_status_label.setObjectName("program_status_label")
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(140, 170, 101, 16))
        self.status_label.setObjectName("status_label")
        self.start_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(50, 230, 61, 21))
        self.start_pushButton.setObjectName("start_pushButton")
        self.end_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.end_pushButton.setGeometry(QtCore.QRect(200, 230, 61, 21))
        self.end_pushButton.setObjectName("end_pushButton")
        self.error_message_lable = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_message_lable.setGeometry(QtCore.QRect(10, 10, 281, 20))
        self.error_message_lable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_message_lable.setObjectName("error_message_lable")
        autoclicker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=autoclicker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 18))
        self.menubar.setObjectName("menubar")
        autoclicker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=autoclicker)
        self.statusbar.setObjectName("statusbar")
        autoclicker.setStatusBar(self.statusbar)

        self.retranslateUi(autoclicker)
        QtCore.QMetaObject.connectSlotsByName(autoclicker)

    def retranslateUi(self, autoclicker):
        _translate = QtCore.QCoreApplication.translate
        autoclicker.setWindowTitle(_translate("autoclicker", "AUTO-Clicker"))
        self.start_click_label.setText(_translate("autoclicker", "Set Start Click button: "))
        self.end_click_label.setText(_translate("autoclicker", "Set End Click Button: "))
        self.delay_label.setText(_translate("autoclicker", "Delay: "))
        self.program_status_label.setText(_translate("autoclicker", "Program status:"))
        self.status_label.setText(_translate("autoclicker", "Status"))
        self.start_pushButton.setText(_translate("autoclicker", "Start"))
        self.end_pushButton.setText(_translate("autoclicker", "End"))
        self.error_message_lable.setText(_translate("autoclicker", "Error mesage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autoclicker = QtWidgets.QMainWindow()
    ui = Ui_autoclicker()
    ui.setupUi(autoclicker)
    autoclicker.show()
    sys.exit(app.exec())
